// <auto-generated />
using System;
using CommerceBankOnlineBanking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CommerceBankOnlineBanking.Migrations
{
    [DbContext(typeof(BankingContext))]
    [Migration("20201122212808_TransactionSeed")]
    partial class TransactionSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("CommerceBankOnlineBanking.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("CommerceBankOnlineBanking.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessingDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transaction");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ddb4852-9899-4493-8d4d-20c8b19a7fc3"),
                            AccountNumber = 1,
                            Action = "Account Open",
                            Amount = 0.0,
                            Balance = 5000.0,
                            Description = "Starting Balance",
                            ProcessingDate = new DateTime(2020, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("097aeda9-59c5-4611-b225-99c0cddf68be")
                        });
                });

            modelBuilder.Entity("CommerceBankOnlineBanking.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad799726-74aa-4d9a-90b9-fb11b4347aff"),
                            FirstName = "Admin",
                            LastName = "Pass",
                            Password = "AEcoeVZIl1+kCRcj4oYJ7PgwTA/kY9tImvbwMS7kJ79IgvPoQgoQmnpwWaAR8zpdog==",
                            UserName = "AdminPass"
                        },
                        new
                        {
                            Id = new Guid("097aeda9-59c5-4611-b225-99c0cddf68be"),
                            FirstName = "Test",
                            LastName = "User",
                            Password = "APbToWW4JNHkNFkqXMVGUdqxEDPBlumQCOA2YT8Yaa6sjKBP3TY2KyHpe8CeY0LAsA==",
                            UserName = "TestUser"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
